#############################################################################
# Makefile for building: OAuthTest.app/Contents/MacOS/OAuthTest
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat May 19 04:00:40 2012
# Project:  OAuthTest.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=release -o Makefile OAuthTest.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.8/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtNetwork.framework/Versions/4/Headers -I/usr/include/QtNetwork -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtWebKit.framework/Versions/4/Headers -I/usr/include/QtWebKit -I/Library/Frameworks/QtDeclarative.framework/Versions/4/Headers -I/usr/include/QtDeclarative -I/usr/include -Ioauth -Itwitter -Iwebpage -IQJson -Iqmlapplicationviewer -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtDeclarative -framework QtScript -framework QtCore -framework QtSvg -framework QtGui -framework QtSql -framework QtXmlPatterns -framework QtNetwork -framework QtWebKit 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		oauth/oauth.cpp \
		oauth/oauth_p.cpp \
		twitter/twitter.cpp \
		webpage/webpage.cpp \
		webpage/page.cpp \
		webpage/networkaccessmanager.cpp \
		QJson/json_parser.cc \
		QJson/json_scanner.cpp \
		QJson/qjson.cpp \
		QJson/parserrunnable.cpp \
		QJson/qobjecthelper.cpp \
		QJson/serializer.cpp \
		QJson/serializerrunnable.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc_oauth.cpp \
		moc_oauth_p.cpp \
		moc_twitter.cpp \
		moc_webpage.cpp \
		moc_page.cpp \
		moc_networkaccessmanager.cpp \
		moc_qjson.cpp \
		moc_parserrunnable.cpp \
		moc_serializerrunnable.cpp \
		moc_qmlapplicationviewer.cpp \
		qrc_cacert.cpp
OBJECTS       = main.o \
		oauth.o \
		oauth_p.o \
		twitter.o \
		webpage.o \
		page.o \
		networkaccessmanager.o \
		json_parser.o \
		json_scanner.o \
		qjson.o \
		parserrunnable.o \
		qobjecthelper.o \
		serializer.o \
		serializerrunnable.o \
		qmlapplicationviewer.o \
		moc_oauth.o \
		moc_oauth_p.o \
		moc_twitter.o \
		moc_webpage.o \
		moc_page.o \
		moc_networkaccessmanager.o \
		moc_qjson.o \
		moc_parserrunnable.o \
		moc_serializerrunnable.o \
		moc_qmlapplicationviewer.o \
		qrc_cacert.o
DIST          = /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-base.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-macx.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		oauth/oauth.pri \
		twitter/twitter.pri \
		webpage/webpage.pri \
		QJson/json.pri \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		/usr/local/Qt4.8/mkspecs/features/release.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		OAuthTest.pro
QMAKE_TARGET  = OAuthTest
DESTDIR       = 
TARGET        = OAuthTest.app/Contents/MacOS/OAuthTest

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile OAuthTest.app/Contents/PkgInfo OAuthTest.app/Contents/Resources/empty.lproj OAuthTest.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) OAuthTest.app/Contents/MacOS/ || $(MKDIR) OAuthTest.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OAuthTest.pro  /usr/local/Qt4.8/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-base.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-macx.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		oauth/oauth.pri \
		twitter/twitter.pri \
		webpage/webpage.pri \
		QJson/json.pri \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		/usr/local/Qt4.8/mkspecs/features/release.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtDeclarative.framework/QtDeclarative.prl \
		/Library/Frameworks/QtScript.framework/QtScript.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl \
		/Library/Frameworks/QtSvg.framework/QtSvg.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtSql.framework/QtSql.prl \
		/Library/Frameworks/QtXmlPatterns.framework/QtXmlPatterns.prl \
		/Library/Frameworks/QtNetwork.framework/QtNetwork.prl \
		/Library/Frameworks/QtWebKit.framework/QtWebKit.prl
	$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=release -o Makefile OAuthTest.pro
/usr/local/Qt4.8/mkspecs/common/unix.conf:
/usr/local/Qt4.8/mkspecs/common/mac.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf:
/usr/local/Qt4.8/mkspecs/common/g++-base.conf:
/usr/local/Qt4.8/mkspecs/common/g++-macx.conf:
/usr/local/Qt4.8/mkspecs/qconfig.pri:
/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.8/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.8/mkspecs/features/qt_config.prf:
/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.8/mkspecs/features/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf:
oauth/oauth.pri:
twitter/twitter.pri:
webpage/webpage.pri:
QJson/json.pri:
qmlapplicationviewer/qmlapplicationviewer.pri:
/usr/local/Qt4.8/mkspecs/features/release.prf:
/usr/local/Qt4.8/mkspecs/features/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf:
/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.8/mkspecs/features/warn_on.prf:
/usr/local/Qt4.8/mkspecs/features/qt.prf:
/usr/local/Qt4.8/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.8/mkspecs/features/moc.prf:
/usr/local/Qt4.8/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.8/mkspecs/features/resources.prf:
/usr/local/Qt4.8/mkspecs/features/uic.prf:
/usr/local/Qt4.8/mkspecs/features/yacc.prf:
/usr/local/Qt4.8/mkspecs/features/lex.prf:
/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtDeclarative.framework/QtDeclarative.prl:
/Library/Frameworks/QtScript.framework/QtScript.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
/Library/Frameworks/QtSvg.framework/QtSvg.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtSql.framework/QtSql.prl:
/Library/Frameworks/QtXmlPatterns.framework/QtXmlPatterns.prl:
/Library/Frameworks/QtNetwork.framework/QtNetwork.prl:
/Library/Frameworks/QtWebKit.framework/QtWebKit.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=release -o Makefile OAuthTest.pro

OAuthTest.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) OAuthTest.app/Contents || $(MKDIR) OAuthTest.app/Contents 
	@$(DEL_FILE) OAuthTest.app/Contents/PkgInfo
	@echo "APPL????" >OAuthTest.app/Contents/PkgInfo
OAuthTest.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) OAuthTest.app/Contents/Resources || $(MKDIR) OAuthTest.app/Contents/Resources 
	@touch OAuthTest.app/Contents/Resources/empty.lproj
	
OAuthTest.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) OAuthTest.app/Contents || $(MKDIR) OAuthTest.app/Contents 
	@$(DEL_FILE) OAuthTest.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,OAuthTest,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.8/mkspecs/macx-g++/Info.plist.app >OAuthTest.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/OAuthTest1.0.0 || $(MKDIR) .tmp/OAuthTest1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/OAuthTest1.0.0/ && $(COPY_FILE) --parents oauth/oauth.h oauth/oauth_types.h oauth/oauth_p.h oauth/oauth_helper.h twitter/twitter.h webpage/webpage.h webpage/page.h webpage/networkaccessmanager.h QJson/json_parser.hh QJson/json_scanner.h QJson/location.hh QJson/qjson.h QJson/qjson_p.h QJson/parserrunnable.h QJson/position.hh QJson/qjson_debug.h QJson/qobjecthelper.h QJson/serializer.h QJson/serializerrunnable.h QJson/stack.hh qmlapplicationviewer/qmlapplicationviewer.h .tmp/OAuthTest1.0.0/ && $(COPY_FILE) --parents oauth/cacert.qrc .tmp/OAuthTest1.0.0/ && $(COPY_FILE) --parents main.cpp oauth/oauth.cpp oauth/oauth_p.cpp twitter/twitter.cpp webpage/webpage.cpp webpage/page.cpp webpage/networkaccessmanager.cpp QJson/json_parser.cc QJson/json_scanner.cpp QJson/qjson.cpp QJson/parserrunnable.cpp QJson/qobjecthelper.cpp QJson/serializer.cpp QJson/serializerrunnable.cpp qmlapplicationviewer/qmlapplicationviewer.cpp .tmp/OAuthTest1.0.0/ && (cd `dirname .tmp/OAuthTest1.0.0` && $(TAR) OAuthTest1.0.0.tar OAuthTest1.0.0 && $(COMPRESS) OAuthTest1.0.0.tar) && $(MOVE) `dirname .tmp/OAuthTest1.0.0`/OAuthTest1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/OAuthTest1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r OAuthTest.app
	-$(DEL_FILE) Makefile


first: $(first) copydeploymentfolders

copydeploymentfolders:
	@echo Copying application data... && $(MKDIR) "/Users/diorahman/Develop/hack/OAuthTest/OAuthTest.app/Contents/Resources/qml" && $(COPY_DIR) "/Users/diorahman/Develop/hack/OAuthTest/qml/OAuthTest" "/Users/diorahman/Develop/hack/OAuthTest/OAuthTest.app/Contents/Resources/qml"

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_oauth.cpp moc_oauth_p.cpp moc_twitter.cpp moc_webpage.cpp moc_page.cpp moc_networkaccessmanager.cpp moc_qjson.cpp moc_parserrunnable.cpp moc_serializerrunnable.cpp moc_qmlapplicationviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_oauth.cpp moc_oauth_p.cpp moc_twitter.cpp moc_webpage.cpp moc_page.cpp moc_networkaccessmanager.cpp moc_qjson.cpp moc_parserrunnable.cpp moc_serializerrunnable.cpp moc_qmlapplicationviewer.cpp
moc_oauth.cpp: oauth/oauth_types.h \
		oauth/oauth.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ oauth/oauth.h -o moc_oauth.cpp

moc_oauth_p.cpp: oauth/oauth_types.h \
		oauth/oauth_p.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ oauth/oauth_p.h -o moc_oauth_p.cpp

moc_twitter.cpp: twitter/twitter.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ twitter/twitter.h -o moc_twitter.cpp

moc_webpage.cpp: webpage/webpage.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ webpage/webpage.h -o moc_webpage.cpp

moc_page.cpp: webpage/page.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ webpage/page.h -o moc_page.cpp

moc_networkaccessmanager.cpp: webpage/networkaccessmanager.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ webpage/networkaccessmanager.h -o moc_networkaccessmanager.cpp

moc_qjson.cpp: QJson/qjson.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ QJson/qjson.h -o moc_qjson.cpp

moc_parserrunnable.cpp: QJson/parserrunnable.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ QJson/parserrunnable.h -o moc_parserrunnable.cpp

moc_serializerrunnable.cpp: QJson/serializerrunnable.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ QJson/serializerrunnable.h -o moc_serializerrunnable.cpp

moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qmlapplicationviewer/qmlapplicationviewer.h -o moc_qmlapplicationviewer.cpp

compiler_rcc_make_all: qrc_cacert.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_cacert.cpp
qrc_cacert.cpp: oauth/cacert.qrc \
		oauth/cacert.pem
	/Developer/Tools/Qt/rcc -name cacert oauth/cacert.qrc -o qrc_cacert.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all: webpage.moc
compiler_moc_source_clean:
	-$(DEL_FILE) webpage.moc
webpage.moc: webpage/webpage.h \
		webpage/networkaccessmanager.h \
		webpage/webpage.cpp
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ webpage/webpage.cpp -o webpage.moc

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_moc_source_clean 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

oauth.o: oauth/oauth.cpp oauth/oauth.h \
		oauth/oauth_types.h \
		oauth/oauth_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oauth.o oauth/oauth.cpp

oauth_p.o: oauth/oauth_p.cpp oauth/oauth_p.h \
		oauth/oauth_types.h \
		oauth/oauth.h \
		oauth/oauth_helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oauth_p.o oauth/oauth_p.cpp

twitter.o: twitter/twitter.cpp twitter/twitter.h \
		QJson/qjson.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o twitter.o twitter/twitter.cpp

webpage.o: webpage/webpage.cpp webpage/webpage.h \
		webpage/networkaccessmanager.h \
		webpage.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o webpage.o webpage/webpage.cpp

page.o: webpage/page.cpp webpage/page.h \
		webpage/webpage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o page.o webpage/page.cpp

networkaccessmanager.o: webpage/networkaccessmanager.cpp webpage/networkaccessmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o networkaccessmanager.o webpage/networkaccessmanager.cpp

json_parser.o: QJson/json_parser.cc QJson/json_parser.hh \
		QJson/stack.hh \
		QJson/qjson_p.h \
		QJson/qjson.h \
		QJson/json_scanner.h \
		QJson/qjson_debug.h \
		QJson/location.hh \
		QJson/position.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o json_parser.o QJson/json_parser.cc

json_scanner.o: QJson/json_scanner.cpp QJson/qjson_debug.h \
		QJson/json_scanner.h \
		QJson/qjson_p.h \
		QJson/qjson.h \
		QJson/json_parser.hh \
		QJson/stack.hh \
		QJson/location.hh \
		QJson/position.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o json_scanner.o QJson/json_scanner.cpp

qjson.o: QJson/qjson.cpp QJson/qjson.h \
		QJson/qjson_p.h \
		QJson/json_parser.hh \
		QJson/stack.hh \
		QJson/json_scanner.h \
		QJson/qjson_debug.h \
		QJson/location.hh \
		QJson/position.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjson.o QJson/qjson.cpp

parserrunnable.o: QJson/parserrunnable.cpp QJson/parserrunnable.h \
		QJson/qjson.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parserrunnable.o QJson/parserrunnable.cpp

qobjecthelper.o: QJson/qobjecthelper.cpp QJson/qobjecthelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qobjecthelper.o QJson/qobjecthelper.cpp

serializer.o: QJson/serializer.cpp QJson/serializer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serializer.o QJson/serializer.cpp

serializerrunnable.o: QJson/serializerrunnable.cpp QJson/serializerrunnable.h \
		QJson/parserrunnable.h \
		QJson/serializer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serializerrunnable.o QJson/serializerrunnable.cpp

qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

moc_oauth.o: moc_oauth.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_oauth.o moc_oauth.cpp

moc_oauth_p.o: moc_oauth_p.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_oauth_p.o moc_oauth_p.cpp

moc_twitter.o: moc_twitter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_twitter.o moc_twitter.cpp

moc_webpage.o: moc_webpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_webpage.o moc_webpage.cpp

moc_page.o: moc_page.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_page.o moc_page.cpp

moc_networkaccessmanager.o: moc_networkaccessmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_networkaccessmanager.o moc_networkaccessmanager.cpp

moc_qjson.o: moc_qjson.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qjson.o moc_qjson.cpp

moc_parserrunnable.o: moc_parserrunnable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parserrunnable.o moc_parserrunnable.cpp

moc_serializerrunnable.o: moc_serializerrunnable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serializerrunnable.o moc_serializerrunnable.cpp

moc_qmlapplicationviewer.o: moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmlapplicationviewer.o moc_qmlapplicationviewer.cpp

qrc_cacert.o: qrc_cacert.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_cacert.o qrc_cacert.cpp

####### Install

install_itemfolder_01: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/OAuthTest/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/OAuthTest/qml/ 
	-$(INSTALL_DIR) /Users/diorahman/Develop/hack/OAuthTest/qml/OAuthTest $(INSTALL_ROOT)/opt/OAuthTest/qml/


uninstall_itemfolder_01:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/OAuthTest/qml/OAuthTest
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/OAuthTest/qml/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/OAuthTest/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/OAuthTest/bin/ 
	$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/OAuthTest/bin/OAuthTest.app"
	
	-$(INSTALL_DIR) "OAuthTest.app" "$(INSTALL_ROOT)/opt/OAuthTest/bin/OAuthTest.app"

uninstall_target:  FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/OAuthTest/bin/OAuthTest.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/OAuthTest/bin/ 


install:  install_itemfolder_01 install_target  FORCE

uninstall: uninstall_itemfolder_01 uninstall_target   FORCE

FORCE:

